### ISSUE TITLE
Fails to build on OSX 10.6.8

### ISSUE THREAD

**Issue by ghost** [libxmljs/libxmljs#110]
I've tried building `libxmljs` but couldn't get anywhere. Here's the contents of the log:

```
iMac:libxmljs der$ make
node-waf build
Waf: Entering directory `/Users/der/Node/projects/corejs/node_modules/libxmljs/build'
[ 1/10] cxx: src/libxmljs.cc -> build/Release/src/libxmljs_1.o
[ 2/10] cxx: src/xml_attribute.cc -> build/Release/src/xml_attribute_1.o
[ 3/10] cxx: src/xml_document.cc -> build/Release/src/xml_document_1.o
[ 4/10] cxx: src/xml_element.cc -> build/Release/src/xml_element_1.o
../src/libxmljs.cc:5:30: error: libxml/xmlmemory.h: No such file or directory
In file included from ../src/libxmljs.cc:8:
../src/xml_document.h:5:25: error: libxml/tree.h: No such file or directory
In file included from ../src/xml_element.h:6,
                 from ../src/xml_attribute.h:6,
                 from ../src/xml_attribute.cc:2:
../src/xml_node.h:5:25: error: libxml/tree.h: No such file or directory
../src/xml_document.cc:5:31: error: libxml/HTMLparser.h: No such file or directory
In file included from ../src/xml_document.cc:7:
../src/xml_document.h:5:25: error: libxml/tree.h: No such file or directory
In file included from ../src/xml_document.cc:10:
../src/xml_syntax_error.h:5:29: error: libxml/xmlerror.h: No such file or directory
In file included from ../src/xml_element.h:6,
                 from ../src/xml_element.cc:9:
../src/xml_node.h:5:25: error: libxml/tree.h: No such file or directory
In file included from ../src/xml_element.cc:12:
../src/xml_xpath_context.h:5:26: error: libxml/xpath.h: No such file or directory
In file included from ../src/libxmljs.cc:8:
../src/xml_document.h:18: error: ISO C++ forbids declaration of ‘xmlDoc’ with no type
../src/xml_document.h:18: error: expected ‘;’ before ‘*’ token
../src/xml_document.h:27: error: ‘xmlDoc’ has not been declared
../src/xml_document.h:40: error: expected `)' before ‘*’ token
In file included from ../src/libxmljs.cc:9:
../src/xml_node.h:12: error: ISO C++ forbids declaration of ‘xmlNode’ with no type
../src/xml_node.h:12: error: expected ‘;’ before ‘*’ token
../src/xml_node.h:14: error: expected `)' before ‘*’ token
../src/xml_node.h:35: error: ‘xmlNs’ has not been declared
../src/xml_node.h:36: error: ISO C++ forbids declaration of ‘xmlNs’ with no type
../src/xml_node.h:36: error: expected ‘;’ before ‘*’ token
In file included from ../src/libxmljs.cc:10:
../src/xml_sax_parser.h:57: error: expected ‘,’ or ‘...’ before ‘*’ token
../src/xml_sax_parser.h:58: error: ISO C++ forbids declaration of ‘xmlChar’ with no type
../src/xml_sax_parser.h:61: error: expected ‘,’ or ‘...’ before ‘*’ token
../src/xml_sax_parser.h:61: error: ISO C++ forbids declaration of ‘xmlChar’ with no type
../src/xml_sax_parser.h:65: error: expected ‘,’ or ‘...’ before ‘*’ token
../src/xml_sax_parser.h:72: error: ISO C++ forbids declaration of ‘xmlChar’ with no type
../src/xml_sax_parser.h:76: error: expected ‘,’ or ‘...’ before ‘*’ token
../src/xml_sax_parser.h:78: error: ISO C++ forbids declaration of ‘xmlChar’ with no type
../src/xml_sax_parser.h:82: error: expected ‘,’ or ‘...’ before ‘*’ token
../src/xml_sax_parser.h:83: error: ISO C++ forbids declaration of ‘xmlChar’ with no type
../src/xml_sax_parser.h:86: error: expected ‘,’ or ‘...’ before ‘*’ token
../src/xml_sax_parser.h:86: error: ISO C++ forbids declaration of ‘xmlChar’ with no type
../src/xml_sax_parser.h:89: error: expected ‘,’ or ‘...’ before ‘*’ token
../src/xml_sax_parser.h:89: error: ISO C++ forbids declaration of ‘xmlChar’ with no type
../src/xml_sax_parser.h:102: error: ISO C++ forbids declaration of ‘xmlParserCtxt’ with no type
../src/xml_sax_parser.h:102: error: expected ‘;’ before ‘*’ token
../src/xml_sax_parser.h:104: error: ISO C++ forbids declaration of ‘xmlSAXHandler’ with no type
../src/xml_sax_parser.h:104: error: expected ‘;’ before ‘*’ token
../src/libxmljs.cc: In function ‘void* libxmljs::xmlMemMallocWrap(size_t)’:
../src/libxmljs.cc:25: error: ‘xmlMemMalloc’ was not declared in this scope
../src/libxmljs.cc:33: error: ‘xmlMemUsed’ was not declared in this scope
../src/libxmljs.cc: In function ‘void libxmljs::xmlMemFreeWrap(void*)’:
../src/libxmljs.cc:43: error: ‘xmlMemFree’ was not declared in this scope
../src/libxmljs.cc:55: error: ‘xmlMemUsed’ was not declared in this scope
../src/libxmljs.cc: In function ‘void* libxmljs::xmlMemReallocWrap(void*, size_t)’:
../src/libxmljs.cc:63: error: ‘xmlMemRealloc’ was not declared in this scope
../src/libxmljs.cc:71: error: ‘xmlMemUsed’ was not declared in this scope
../src/libxmljs.cc: In function ‘char* libxmljs::xmlMemoryStrdupWrap(const char*)’:
../src/libxmljs.cc:80: error: ‘xmlMemoryStrdup’ was not declared in this scope
../src/libxmljs.cc:88: error: ‘xmlMemUsed’ was not declared in this scope
../src/libxmljs.cc: In constructor ‘libxmljs::LibXMLJS::LibXMLJS()’:
../src/libxmljs.cc:105: error: ‘xmlMemSetup’ was not declared in this scope
../src/libxmljs.cc:108: error: ‘LIBXML_TEST_VERSION’ was not declared in this scope
../src/libxmljs.cc:111: error: ‘xmlMemUsed’ was not declared in this scope
../src/libxmljs.cc: In destructor ‘virtual libxmljs::LibXMLJS::~LibXMLJS()’:
../src/libxmljs.cc:116: error: ‘xmlCleanupParser’ was not declared in this scope
../src/libxmljs.cc: In function ‘void libxmljs::init(v8::Handle<v8::Object>)’:
../src/libxmljs.cc:132: error: ‘LIBXML_DOTTED_VERSION’ was not declared in this scope
../src/libxmljs.cc:135: error: ‘xmlParserVersion’ was not declared in this scope
In file included from ../src/xml_element.h:6,
                 from ../src/xml_attribute.h:6,
                 from ../src/xml_attribute.cc:2:
../src/xml_node.h:12: error: ISO C++ forbids declaration of ‘xmlNode’ with no type
../src/xml_node.h:12: error: expected ‘;’ before ‘*’ token
../src/xml_node.h:14: error: expected `)' before ‘*’ token
../src/xml_node.h:35: error: ‘xmlNs’ has not been declared
../src/xml_node.h:36: error: ISO C++ forbids declaration of ‘xmlNs’ with no type
../src/xml_node.h:36: error: expected ‘;’ before ‘*’ token
In file included from ../src/xml_attribute.h:6,
                 from ../src/xml_attribute.cc:2:
../src/xml_element.h:13: error: expected `)' before ‘*’ token
../src/xml_element.h:20: error: ‘xmlNode’ has not been declared
In file included from ../src/xml_attribute.h:7,
                 from ../src/xml_attribute.cc:2:
../src/xml_namespace.h:14: error: ISO C++ forbids declaration of ‘xmlNs’ with no type
../src/xml_namespace.h:14: error: expected ‘;’ before ‘*’ token
../src/xml_namespace.h:19: error: expected `)' before ‘*’ token
../src/xml_namespace.h:20: error: expected `)' before ‘*’ token
../src/xml_namespace.h:23: error: ‘xmlNs’ has not been declared
In file included from ../src/xml_attribute.cc:2:
../src/xml_attribute.h:14: error: expected `)' before ‘*’ token
../src/xml_attribute.h:20: error: ‘xmlNode’ has not been declared
../src/xml_attribute.h:21: error: expected ‘,’ or ‘...’ before ‘*’ token
../src/xml_attribute.h:21: error: ISO C++ forbids declaration of ‘xmlChar’ with no type
../src/xml_attribute.h:23: error: ‘xmlAttr’ has not been declared
../src/xml_attribute.cc:16: error: ‘v8::Handle<v8::Object> libxmljs::XmlAttribute::New’ is not a static member of ‘class libxmljs::XmlAttribute’
../src/xml_attribute.cc:16: error: ‘xmlNode’ was not declared in this scope
../src/xml_attribute.cc:16: error: ‘xml_obj’ was not declared in this scope
../src/xml_attribute.cc:16: error: expected primary-expression before ‘const’
../src/xml_attribute.cc:16: error: expected primary-expression before ‘const’
../src/xml_attribute.cc:17: error: expected ‘,’ or ‘;’ before ‘{’ token
../src/xml_attribute.cc:152: error: expected `}' at end of input
In file included from ../src/xml_document.cc:7:
../src/xml_document.h:18: error: ISO C++ forbids declaration of ‘xmlDoc’ with no type
../src/xml_document.h:18: error: expected ‘;’ before ‘*’ token
../src/xml_document.h:27: error: ‘xmlDoc’ has not been declared
../src/xml_document.h:40: error: expected `)' before ‘*’ token
In file included from ../src/xml_element.h:6,
                 from ../src/xml_document.cc:8:
../src/xml_node.h:12: error: ISO C++ forbids declaration of ‘xmlNode’ with no type
../src/xml_node.h:12: error: expected ‘;’ before ‘*’ token
../src/xml_node.h:14: error: expected `)' before ‘*’ token
../src/xml_node.h:35: error: ‘xmlNs’ has not been declared
../src/xml_node.h:36: error: ISO C++ forbids declaration of ‘xmlNs’ with no type
../src/xml_node.h:36: error: expected ‘;’ before ‘*’ token
In file included from ../src/xml_document.cc:8:
../src/xml_element.h:13: error: expected `)' before ‘*’ token
../src/xml_element.h:20: error: ‘xmlNode’ has not been declared
In file included from ../src/xml_document.cc:9:
../src/xml_namespace.h:14: error: ISO C++ forbids declaration of ‘xmlNs’ with no type
../src/xml_namespace.h:14: error: expected ‘;’ before ‘*’ token
../src/xml_namespace.h:19: error: expected `)' before ‘*’ token
../src/xml_namespace.h:20: error: expected `)' before ‘*’ token
../src/xml_namespace.h:23: error: ‘xmlNs’ has not been declared
In file included from ../src/xml_document.cc:10:
../src/xml_syntax_error.h:16: error: ‘xmlError’ has not been declared
../src/xml_syntax_error.h:20: error: ‘xmlError’ has not been declared
../src/xml_document.cc: In static member function ‘static v8::Handle<v8::Value> libxmljs::XmlDocument::Encoding(const v8::Arguments&)’:
../src/xml_document.cc:25: error: ‘class libxmljs::XmlDocument’ has no member named ‘xml_obj’
../src/xml_document.cc:27: error: ‘class libxmljs::XmlDocument’ has no member named ‘xml_obj’
../src/xml_document.cc:28: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_document.cc:28: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_document.cc:28: error: expected primary-expression before ‘const’
../src/xml_document.cc:28: error: expected `)' before ‘const’
../src/xml_document.cc:35: error: ‘class libxmljs::XmlDocument’ has no member named ‘xml_obj’
../src/xml_document.cc:36: error: ‘xmlChar’ was not declared in this scope
../src/xml_document.cc:36: error: expected primary-expression before ‘)’ token
../src/xml_document.cc:36: error: ‘xmlFree’ was not declared in this scope
../src/xml_document.cc:39: error: ‘class libxmljs::XmlDocument’ has no member named ‘xml_obj’
../src/xml_document.cc:39: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_document.cc:39: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_document.cc:39: error: expected primary-expression before ‘const’
../src/xml_document.cc:39: error: expected `)' before ‘const’
../src/xml_document.cc: In static member function ‘static v8::Handle<v8::Value> libxmljs::XmlDocument::Version(const v8::Arguments&)’:
../src/xml_document.cc:50: error: ‘class libxmljs::XmlDocument’ has no member named ‘xml_obj’
../src/xml_document.cc:51: error: ‘class libxmljs::XmlDocument’ has no member named ‘xml_obj’
../src/xml_document.cc:52: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_document.cc:52: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_document.cc:52: error: expected primary-expression before ‘const’
../src/xml_document.cc:52: error: expected `)' before ‘const’
../src/xml_document.cc: In static member function ‘static v8::Handle<v8::Value> libxmljs::XmlDocument::Root(const v8::Arguments&)’:
../src/xml_document.cc:64: error: ‘xmlNode’ was not declared in this scope
../src/xml_document.cc:64: error: ‘root’ was not declared in this scope
../src/xml_document.cc:64: error: ‘class libxmljs::XmlDocument’ has no member named ‘xml_obj’
../src/xml_document.cc:64: error: ‘xmlDocGetRootElement’ was not declared in this scope
../src/xml_document.cc:83: error: ‘class libxmljs::XmlDocument’ has no member named ‘xml_obj’
../src/xml_document.cc:83: error: ‘class libxmljs::XmlElement’ has no member named ‘xml_obj’
../src/xml_document.cc:83: error: ‘xmlDocSetRootElement’ was not declared in this scope
../src/xml_document.cc: In static member function ‘static v8::Handle<v8::Value> libxmljs::XmlDocument::ToString(const v8::Arguments&)’:
../src/xml_document.cc:95: error: ‘xmlChar’ was not declared in this scope
../src/xml_document.cc:95: error: ‘buffer’ was not declared in this scope
../src/xml_document.cc:97: error: ‘class libxmljs::XmlDocument’ has no member named ‘xml_obj’
../src/xml_document.cc:97: error: ‘xmlDocDumpFormatMemoryEnc’ was not declared in this scope
../src/xml_document.cc:99: error: ‘xmlFree’ was not declared in this scope
../src/xml_document.cc: At global scope:
../src/xml_document.cc:107: error: ‘v8::Handle<v8::Object> libxmljs::XmlDocument::New’ is not a static member of ‘class libxmljs::XmlDocument’
../src/xml_document.cc:107: error: ‘xmlDoc’ was not declared in this scope
../src/xml_document.cc:107: error: ‘doc’ was not declared in this scope
../src/xml_document.cc:108: error: expected ‘,’ or ‘;’ before ‘{’ token
../src/xml_document.cc:264: error: expected `}' at end of input
In file included from ../src/xml_element.h:6,
                 from ../src/xml_element.cc:9:
../src/xml_node.h:12: error: ISO C++ forbids declaration of ‘xmlNode’ with no type
../src/xml_node.h:12: error: expected ‘;’ before ‘*’ token
../src/xml_node.h:14: error: expected `)' before ‘*’ token
../src/xml_node.h:35: error: ‘xmlNs’ has not been declared
../src/xml_node.h:36: error: ISO C++ forbids declaration of ‘xmlNs’ with no type
../src/xml_node.h:36: error: expected ‘;’ before ‘*’ token
In file included from ../src/xml_element.cc:9:
../src/xml_element.h:13: error: expected `)' before ‘*’ token
../src/xml_element.h:20: error: ‘xmlNode’ has not been declared
In file included from ../src/xml_element.cc:10:
../src/xml_document.h:18: error: ISO C++ forbids declaration of ‘xmlDoc’ with no type
../src/xml_document.h:18: error: expected ‘;’ before ‘*’ token
../src/xml_document.h:27: error: ‘xmlDoc’ has not been declared
../src/xml_document.h:40: error: expected `)' before ‘*’ token
In file included from ../src/xml_attribute.h:7,
                 from ../src/xml_element.cc:11:
../src/xml_namespace.h:14: error: ISO C++ forbids declaration of ‘xmlNs’ with no type
../src/xml_namespace.h:14: error: expected ‘;’ before ‘*’ token
../src/xml_namespace.h:19: error: expected `)' before ‘*’ token
../src/xml_namespace.h:20: error: expected `)' before ‘*’ token
../src/xml_namespace.h:23: error: ‘xmlNs’ has not been declared
In file included from ../src/xml_element.cc:11:
../src/xml_attribute.h:14: error: expected `)' before ‘*’ token
../src/xml_attribute.h:20: error: ‘xmlNode’ has not been declared
../src/xml_attribute.h:21: error: expected ‘,’ or ‘...’ before ‘*’ token
../src/xml_attribute.h:21: error: ISO C++ forbids declaration of ‘xmlChar’ with no type
../src/xml_attribute.h:23: error: ‘xmlAttr’ has not been declared
In file included from ../src/xml_element.cc:12:
../src/xml_xpath_context.h:14: error: expected `)' before ‘*’ token
../src/xml_xpath_context.h:17: error: expected ‘,’ or ‘...’ before ‘*’ token
../src/xml_xpath_context.h:17: error: ISO C++ forbids declaration of ‘xmlChar’ with no type
../src/xml_xpath_context.h:18: error: expected ‘,’ or ‘...’ before ‘*’ token
../src/xml_xpath_context.h:18: error: ISO C++ forbids declaration of ‘xmlChar’ with no type
../src/xml_xpath_context.h:20: error: ISO C++ forbids declaration of ‘xmlXPathContext’ with no type
../src/xml_xpath_context.h:20: error: expected ‘;’ before ‘*’ token
../src/xml_element.cc: In static member function ‘static v8::Handle<v8::Value> libxmljs::XmlElement::New(const v8::Arguments&)’:
../src/xml_element.cc:41: error: ‘xmlNode’ was not declared in this scope
../src/xml_element.cc:41: error: ‘elem’ was not declared in this scope
../src/xml_element.cc:41: error: ‘class libxmljs::XmlDocument’ has no member named ‘xml_obj’
../src/xml_element.cc:43: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:43: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:43: error: expected primary-expression before ‘const’
../src/xml_element.cc:43: error: expected `)' before ‘const’
../src/xml_element.cc: In static member function ‘static v8::Handle<v8::Value> libxmljs::XmlElement::Find(const v8::Arguments&)’:
../src/xml_element.cc:129: error: ‘class libxmljs::XmlElement’ has no member named ‘xml_obj’
../src/xml_element.cc:134: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:134: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:134: error: expected primary-expression before ‘const’
../src/xml_element.cc:134: error: expected `)' before ‘const’
../src/xml_element.cc:144: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:144: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:144: error: expected primary-expression before ‘const’
../src/xml_element.cc:144: error: expected `)' before ‘const’
../src/xml_element.cc:149: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:149: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:149: error: expected primary-expression before ‘const’
../src/xml_element.cc:149: error: expected `)' before ‘const’
../src/xml_element.cc: In member function ‘void libxmljs::XmlElement::set_name(const char*)’:
../src/xml_element.cc:255: error: ‘xml_obj’ was not declared in this scope
../src/xml_element.cc:255: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:255: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:255: error: expected primary-expression before ‘const’
../src/xml_element.cc:255: error: expected `)' before ‘const’
../src/xml_element.cc: In member function ‘v8::Handle<v8::Value> libxmljs::XmlElement::get_name()’:
../src/xml_element.cc:260: error: ‘xml_obj’ was not declared in this scope
../src/xml_element.cc: In member function ‘v8::Handle<v8::Value> libxmljs::XmlElement::get_attr(const char*)’:
../src/xml_element.cc:268: error: ‘xmlAttr’ was not declared in this scope
../src/xml_element.cc:268: error: ‘attr’ was not declared in this scope
../src/xml_element.cc:268: error: ‘xml_obj’ was not declared in this scope
../src/xml_element.cc:268: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:268: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:268: error: expected primary-expression before ‘const’
../src/xml_element.cc:268: error: expected `)' before ‘const’
../src/xml_element.cc: In member function ‘void libxmljs::XmlElement::set_attr(const char*, const char*)’:
../src/xml_element.cc:283: error: ‘xml_obj’ was not declared in this scope
../src/xml_element.cc:283: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:283: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:283: error: expected primary-expression before ‘const’
../src/xml_element.cc:283: error: expected `)' before ‘const’
../src/xml_element.cc: In member function ‘v8::Handle<v8::Value> libxmljs::XmlElement::get_attrs()’:
../src/xml_element.cc:289: error: ‘xmlAttr’ was not declared in this scope
../src/xml_element.cc:289: error: ‘attr’ was not declared in this scope
../src/xml_element.cc:289: error: ‘xml_obj’ was not declared in this scope
../src/xml_element.cc: In member function ‘void libxmljs::XmlElement::add_child(libxmljs::XmlElement*)’:
../src/xml_element.cc:308: error: ‘xml_obj’ was not declared in this scope
../src/xml_element.cc:308: error: ‘class libxmljs::XmlElement’ has no member named ‘xml_obj’
../src/xml_element.cc:308: error: ‘xmlAddChild’ was not declared in this scope
../src/xml_element.cc: In member function ‘v8::Handle<v8::Value> libxmljs::XmlElement::get_child(int32_t)’:
../src/xml_element.cc:314: error: ‘xmlNode’ was not declared in this scope
../src/xml_element.cc:314: error: ‘child’ was not declared in this scope
../src/xml_element.cc:314: error: ‘xml_obj’ was not declared in this scope
../src/xml_element.cc: In member function ‘v8::Handle<v8::Value> libxmljs::XmlElement::get_child_nodes()’:
../src/xml_element.cc:332: error: ‘xmlNode’ was not declared in this scope
../src/xml_element.cc:332: error: ‘child’ was not declared in this scope
../src/xml_element.cc:332: error: ‘xml_obj’ was not declared in this scope
../src/xml_element.cc: In member function ‘v8::Handle<v8::Value> libxmljs::XmlElement::get_path()’:
../src/xml_element.cc:354: error: ‘xmlChar’ was not declared in this scope
../src/xml_element.cc:354: error: ‘path’ was not declared in this scope
../src/xml_element.cc:354: error: ‘xml_obj’ was not declared in this scope
../src/xml_element.cc:354: error: ‘xmlGetNodePath’ was not declared in this scope
../src/xml_element.cc:356: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:356: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:356: error: expected primary-expression before ‘const’
../src/xml_element.cc:356: error: expected `)' before ‘const’
../src/xml_element.cc:358: error: ‘xmlFree’ was not declared in this scope
../src/xml_element.cc: In member function ‘void libxmljs::XmlElement::set_content(const char*)’:
../src/xml_element.cc:364: error: ‘xml_obj’ was not declared in this scope
../src/xml_element.cc:364: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:364: error: ISO C++ forbids declaration of ‘type name’ with no type
../src/xml_element.cc:364: error: expected primary-expression before ‘const’
../src/xml_element.cc:364: error: expected `)' before ‘const’
../src/xml_element.cc: In member function ‘v8::Handle<v8::Value> libxmljs::XmlElement::get_content()’:
../src/xml_element.cc:369: error: ‘xmlChar’ was not declared in this scope
../src/xml_element.cc:369: error: ‘content’ was not declared in this scope
../src/xml_element.cc:369: error: ‘xml_obj’ was not declared in this scope
../src/xml_element.cc:369: error: ‘xmlNodeGetContent’ was not declared in this scope
../src/xml_element.cc:373: error: ‘xmlFree’ was not declared in this scope
../src/xml_element.cc: In member function ‘v8::Handle<v8::Value> libxmljs::XmlElement::get_next_element()’:
../src/xml_element.cc:384: error: ‘xmlNode’ was not declared in this scope
../src/xml_element.cc:384: error: ‘sibling’ was not declared in this scope
../src/xml_element.cc:384: error: ‘xml_obj’ was not declared in this scope
../src/xml_element.cc:388: error: ‘XML_ELEMENT_NODE’ was not declared in this scope
../src/xml_element.cc: In member function ‘v8::Handle<v8::Value> libxmljs::XmlElement::get_prev_element()’:
../src/xml_element.cc:402: error: ‘xmlNode’ was not declared in this scope
../src/xml_element.cc:402: error: ‘sibling’ was not declared in this scope
../src/xml_element.cc:402: error: ‘xml_obj’ was not declared in this scope
../src/xml_element.cc:406: error: ‘XML_ELEMENT_NODE’ was not declared in this scope
../src/xml_element.cc: At global scope:
../src/xml_element.cc:418: error: ‘v8::Handle<v8::Object> libxmljs::XmlElement::New’ is not a static member of ‘class libxmljs::XmlElement’
../src/xml_element.cc:418: error: ‘xmlNode’ was not declared in this scope
../src/xml_element.cc:418: error: expected primary-expression before ‘)’ token
../src/xml_element.cc:419: error: expected ‘,’ or ‘;’ before ‘{’ token
../src/xml_element.cc:532: error: expected `}' at end of input
Waf: Leaving directory `/Users/der/Node/projects/corejs/node_modules/libxmljs/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx libxmljs.cc -> libxmljs_1.o}
 -> task failed (err #1): 
    {task: cxx xml_attribute.cc -> xml_attribute_1.o}
 -> task failed (err #1): 
    {task: cxx xml_document.cc -> xml_document_1.o}
 -> task failed (err #1): 
    {task: cxx xml_element.cc -> xml_element_1.o}
make: *** [build/Release/libxmljs.node] Error 1
```

I installed `libxml` using macports, with `sudo port install libxml`, and here are the contents of the `libxml` package:

```
iMac:Work der$ port contents libxml
Port libxml contains:
  /opt/local/bin/xml-config
  /opt/local/include/gnome-xml/HTMLparser.h
  /opt/local/include/gnome-xml/HTMLtree.h
  /opt/local/include/gnome-xml/SAX.h
  /opt/local/include/gnome-xml/debugXML.h
  /opt/local/include/gnome-xml/encoding.h
  /opt/local/include/gnome-xml/entities.h
  /opt/local/include/gnome-xml/libxml
  /opt/local/include/gnome-xml/nanoftp.h
  /opt/local/include/gnome-xml/nanohttp.h
  /opt/local/include/gnome-xml/parser.h
  /opt/local/include/gnome-xml/parserInternals.h
  /opt/local/include/gnome-xml/tree.h
  /opt/local/include/gnome-xml/uri.h
  /opt/local/include/gnome-xml/valid.h
  /opt/local/include/gnome-xml/xlink.h
  /opt/local/include/gnome-xml/xml-error.h
  /opt/local/include/gnome-xml/xmlIO.h
  /opt/local/include/gnome-xml/xmlmemory.h
  /opt/local/include/gnome-xml/xpath.h
  /opt/local/lib/libxml.1.dylib
  /opt/local/lib/libxml.dylib
  /opt/local/lib/libxml.la
  /opt/local/lib/pkgconfig/libxml.pc
  /opt/local/lib/xmlConf.sh
  /opt/local/share/gnome-xml/html/gnome-xml/DOM.gif
  /opt/local/share/gnome-xml/html/gnome-xml/book1.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-debugxml.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-encoding.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-entities.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-error.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-htmlparser.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-htmltree.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-nanoftp.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-nanohttp.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-parser.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-parserinternals.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-sax.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-tree.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-valid.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-xml-error.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-xmlio.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-xmlmemory.html
  /opt/local/share/gnome-xml/html/gnome-xml/gnome-xml-xpath.html
  /opt/local/share/gnome-xml/html/gnome-xml/index.sgml
  /opt/local/share/gnome-xml/html/gnome-xml/libxml-lib.html
  /opt/local/share/gnome-xml/html/gnome-xml/libxml-notes.html
  /opt/local/share/gnome-xml/html/gnome-xml/structure.gif
  /opt/local/share/gnome-xml/html/gnome-xml/xml.html
```

Not quite sure, maybe I don't have libxml (properly) installed on my system ? I hope this info is helpful so you guys can fix the problem (if there's any).

Thanks a ton,
Ernie.-
